name: Check OpenAPI Specification on Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - 'reference/*'

jobs:
  lint:
    uses: ./.github/workflows/lint-spec.yml
  test:
    needs:
      - lint
    uses: ./.github/workflows/test-spec.yml
