name: Lint OpenAPI Specification

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install -g @stoplight/spectral-cli
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Lint OpenAPI Specification
        run: spectral lint -f sarif reference/spec.yaml | reviewdog -f=sarif -diff="git diff" -reporter=github-check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
